server:
  port: 8123
  tomcat:
    threads:
      max: 100
spring:
  profiles:
    active: local
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/foresty
      username: root
      password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/foresty
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
        use_sql_comments: true
    generate-ddl: true
    show-sql: true
    open-in-view: true
  output:
    ansi:
      enabled: always
logging:
  level:
    root: info
    org.hibernate.sql: trace